blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from website import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/writterarea/', views.writterArea, name= 'writterarea'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/website/urls.py
from django.urls import path
from website import views

app_name = 'website'

urlpatterns = [
    path('', views.indexPage, name = 'index'),
    path('writterspage/<str:writter_slug>/', views.writtersPage, name = 'writterpage'),
    path('pubpage/<str:pub_slug>/', views.pubPage, name = 'pubpage'),
    path('resultpage/', views.resultPage, name = 'resultpage'),
    path('aboutus/', views.aboutusPage, name = 'aboutuspage'),
    path('user/', views.loginPage, name = 'loginpage'),
    path('user/user/', views.checkLogin),
    path('accounts/login/writterarea/postpub/', views.postPub, name = 'postpub'),
    path('accounts/login/writterarea/whatdo/', views.whatDo, name = 'whatdo'),
    path('accounts/login/writterarea/updatepub/<int:pub_id>/', views.updatePub, name = 'updatepub'),
]

blog/website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
   

class Publication(models.Model):
    title = models.CharField(max_length = 100)
    text = models.TextField(null = True)
    date = models.DateField()
    view_number = models.IntegerField(default = 0)
    writter = models.ForeignKey(User, on_delete = models.CASCADE)
    photo = models.FileField(upload_to = 'images/website/pubs', null = True)
    slug = models.SlugField(unique = True, blank = True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Publication, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.title
    
    

blog/website/forms.py
from django import forms
from website.models import Publication as pub 

class PubForm(forms.ModelForm):
    class Meta:
        model = pub 
        exclude = ['slug', 'writter', 'view_number']
        
        

blog/website/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from website.models import Publication
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.urls import reverse

# the import bellow is used to store values 
from .forms import PubForm



def indexPage(request):
    return render(request, 'website/index.html', {
        'newpubs':Publication.objects.order_by('date')[0:5]
    })
 
def writtersPage(request, writter_slug):
    return HttpReponse('Writters page') 
    
    """
    render(request, 'website/writterspage.html',{
        'writter' : Writter.objects.get(slug = writter_slug)
    })
    """    

def pubPage(request, pub_slug):
    pub = Publication.objects.filter(slug = pub_slug)[0]
    pub.view_number = pub.view_number + 1
    pub.save()
    
    return render(request, 'website/pub.html', {
        'pub' : pub
    }) 
    
def resultPage(request):
    return render(request, 'website/result.html', {
        'pubs' : Publication.objects.filter(title__contains = request.POST.get('search'))
    })
    
def aboutusPage(request):
    return render(request, 'website/aboutus.html')
    
def loginPage(request):
    return render(request, 'website/loginpage.html')
    
def checkLogin(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username = username, password = password)
    
    if user is not None:
        return render(request, 'website/writterarea.html', {'pubs' : Publication.objects.all()})
    else:
        return render(request, 'website/loginpage.html', {'error' : 'You made some mistake. Try again.'}) 
        
    
def postPub(request):
    pub = Publication()
    pub.title = request.POST.get('title')
    pub.date = request.POST.get('date')
    pub.photo = request.POST.get('photo')
    pub.writter =  request.user
    pub.text = request.POST.get('text')
    
    pub.save()
    
    return HttpResponseRedirect(reverse('writterarea', args=()))

        
def writterArea(request):
    pubs = Publication.objects.filter(writter = request.user.id)
    
    form = PubForm()
    
    return render(request, 'website/wt_area.html', {'pubs' : pubs, 'form' : form})
    
def whatDo(request):
    whatdo = request.POST.get('whatdo')
    pubs = request.POST.get('pubs')
    
    Publication.objects.filter(title= request.POST.get('pubs')).delete()
    
    return HttpResponseRedirect(reverse('writterarea', args=()))
    
def updatePub(request, pub_id):
    if request.method == 'POST': 
        if form.is_valid():
            pub = Publication.objects.filter(writter = request.user)[0]
            pub.title = request.POST.get('title')
            pub.text = request.POST.get('text')
            pub.photo = request.POST.get('photo')
            pub.writter = request.user 
           
            pub.save()
       
        return HttpResponseRedirect(reverse('writterarea'))
    else: 
        pub = Publication.objects.get(id = pub_id)
        pubform = PubForm(instance = pub) 
       
        return render(request, 'website/updatepub.html', {'form' : pubform, 'pub_id' : pub_id})
        

blog/templates/website/aboutus.html
{% extends 'website/base.html' %}

{% block content_space %}
	<h3 class="title">About us</h3>
	
	<p>Hello! Welcome to our about us page.</p>
	
	<p>The Economics and Society website was created to help people that are starting to learn
	about ecnomics and the relationship with the society. The website was created by an Economist 
	and a programmer, both likening the Economics studies.</p>
	
	<p>The website was originally released in 2015, and the publications staryed to be written in 2016.
	As the pubs were released, the people started to come, read and stay with us, making many comments and
	wanting to help us with new articles. So in this time, we started to take people to work with us, volunteers.
	Now we have 100 volunters who works writting the articles, reviewing and checking the grammar to make a good
	document, which a begginner can understand easily. Furthermore, we also have 30 people who works with us, maintening
	the website, updating it. These aren't volunters, we pay these guys</p>
	
	<p>Today, the Economics and Society website is one of the biggest websites about Economics and Society in the world,
	having many branchs in many countries like: United States, United Kingdom, Brazil, Singapure, China, France, Mexico, 
	etc.</p>
	
	<p>That's it. Thank you for your attention, Have a great day.</p>
{% endblock %}

blog/templates/website/base.html
<!DOCUMENT html>
{% load static %}

<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<script>
  	$(document).ready(function() {

	var docHeight = $(window).height();
	var footerHeight = $('#footer').height();
	var footerTop = $('#footer').position().top + footerHeight;

	if (footerTop < docHeight) {
    	$('#footer').css('margin-top', 10+ (docHeight - footerTop) + 'px');
	}
  });
 
		</script>
	</head>
	
	<body>
		<header>
			<a href="{% url 'website:index' %}"><h2 class="title">Economics and Society</h2></a>
			
			<a href="{% url 'website:aboutuspage' %}">ABOUT US</a>
			<a href="{% url 'website:index' %}">INDEX</a>
		</header>
		
		<div id="bodydiv">
			<div id="bar_menu">
				<div id="search_part">
					<form action="{% url 'website:resultpage' %}" method="post">
						{% csrf_token %}
						<label for="search">Search</label>
						<input type="text" name="search" placeholder="Type here">
					</form>
				</div>
				
				<div class="iframe_block">
					<h3>Most viewed pubs</h3>
					
					{% if mv_pubs %}
						<ul>
							{% for pub in mv_pubs %}
								<li><a href="{% url 'website:pubpage' pub.slug %}">{{ pub.title }}</a></li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>
				
				<div class="iframe_block">
					<h3>The writters</h3>
					
					{% if writters %}
						<ul>
							{% for writter in writters %}
								<li><a href="{% url 'website:writterpage' writter.slug %}">{{ writter.name }}</a></li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>
				
				<div class="iframe_block">
					<h3>Most recent pubs</h3>
					
					{% if mr_pubs %}
						<ul>
							{% for pub in mr_pubs %}
								<li><a href="{% url 'website:pubpage' pub.slug %}">{{ pub.title }}</a></li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>
			</div>
			
			<div id="content_space">
				{% block content_space %}
				{% endblock %}
			</div>
		</div>
		
		<footer>
			<h3>Economics and Society </h3>
			<h5>All rights reserved</h5>
		</footer>
	</body>
</html>

blog/templates/website/index.html
<!DOCUMENT html>
{% extends 'website/base.html' %}
{% load static %}

{% block content_space %}
	{% if newpubs %}
		{% for pub in newpubs %}
			<a href="{% url 'website:pubpage' pub.slug %}">
				<div class="pubs">
					<h3>{{pub.title}}</h3>
					<span class="pub_infos"><a href="">{{pub.writter}}</a><br>{{pub.date}}</span><br><br>
				
					{{ pub.text|truncatechars:250 }}
				</div>
			</a>
		{% endfor %}
	{% endif %}
{% endblock %}

blog/templates/website/loginpage.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
	<body>
		<div class="login_block">
			<img src="{% static 'images/login.png' %}">
			
			<a href="{% url 'website:index' %}">Index</a>
			
			<form method="post" action="user/">
				{% csrf_token %}
			
				{% if error %}
					<p style="text-align:center;">{{ error }}</p>
				{% endif %}
			
				<label for="username">Insert your username bellow</label> <br><br>
				<input type="textarea" name="username" placeholder="Put your username here"> <br><br>
				
				<label for="password">Put your password below</label> <br><br>
				<input type="password" name="password" placeholder="Put your password here"> <br><br>
				
				<input type="submit" value="Login" class="btn">
			</form>
		</div>
	</body>
</html>

blog/templates/website/mviewedpubs.html
<!DOCUMENT html>
<html>
	<head>
	
	</head>
	
	<body>
	
	</body>
</html>

blog/templates/website/name.html
<!DOCTYPE html>

<html>
	<head>
	
	</head>
	<body>
		<form action="{% url 'website:name' %}" method='POST'>
			{% csrf_token %}
			
			{{ form.as_p }}
			<input type='submit' value='submit'>
		</form>
	</body>
</html>

blog/templates/website/pub.html
{% extends 'website/base.html' %}
{% load static %}

{% block content_space %}
	<h3 class="title">{{pub.title}}</h3>
	
	<div class="pub_infos">
		<a href="">{{pub.writter}}</a><br> {{pub.date}} <br> {{pub.view_number}} <br><br><br></span>
	</div>
	
	<div id="pub_image">
		<figure>
			<img src="{{MEDIA_URL}}{{pub.photo}}" style="height:30%; width:80%;">
			
			<figcaption>{{ MEDIA_URL }}{{ pub.photo }}</figcaption>
		</figure>
		
	</div>	

	
	{{pub.text}}
{% endblock %}

blog/templates/website/result.html
{% extends 'website/base.html' %}

{% block content_space %}
	<h3 class="title">Showing results</h3>
	{% if pubs %}
		{% for pub in pubs %}
			<div class="pubs">
				<a href="{% url 'website:pubpage' pub.slug %}"><h3>{{pub.title}}</h3></a>
				
				{{pub.text|truncatechars:250}}
			</div>
		{% endfor %}
	{% endif %}
{% endblock %}

blog/templates/website/updatepub.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
	<body>
		<header>
			<a href="{% url 'writterarea' %}">Come back</a>
		</header>
		
		<div class="update_div">
			<form method='post' action="{% url 'website:updatepub' pub_id %}">
				{% csrf_token %}
				{{ form.errors }}
				{{ form.as_p }}
				
				<input type='submit' value='ok' class="btn" height="50px"> 
			</form>
		</div>
	</body>
</html>

blog/templates/website/writterarea.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<style>
			header{
				height:50px;
				color:white;
			}
			
			#pubs_div{
				width:30%;
				height:100%;
				border-right: 1px solid;
				background-color:rgba(200,200,200,0.5);
				display:inline;
				float:left;
			}
			
			#form_div{
				width:65%;
				margin: 0 2% 0 1%;
				background-color:rgba(255,255,0,0.1);
				float:right;
			}
			
			a{
				text-decoration:none;
			}
		</style>
	</head>
	<body>
		<header>
			<p>Hello, {{ request.user.username }} </p>
		</header>
		
		<div id='pubs_div'>
			{% if user.is_authenticated %}
				<h1>You are authenticated and logged in</h1>
			{% else %}
				<h1>You aren't authenticated and not logged in. Try again</h1>
			{% endif %}
			
			<h3 class='title'>My Pubs</h3>
			{% if pubs %}
				<form>
					What to do: <select name='whatdo'>
						<option value='delete'>Delete the selected pubs</option>					
					</select> 
					<input type='submit' value='Go'><br><br>
					
					{% for pub in pubs %}
						<input type='checkbox' id='{{ pub.title }}' name='pubs' value='{{ pub.title }}'>
						<a href=''>{{ pub.title }}</a><br><br>
					{% endfor %}
				</form>
			{% endif %}
		</div>
		
		<div id='form_div'>
			<h3 class='title'>Add New Pub</h3>
			
			<form method='post' action='postpub/'>
				{% csrf_token %}
			
				<label for='title'>Title: </label>
				<input type='text' name='title'><br><br>
				
				<label for='date'>Date: </label>
				<input type='date' name='date'><br><br>
				
				<label for='image'>Photo: </label>
				<input type='file' name='image'><br><br>
				
				<input type='hidden' name='writter' value='{{ request.user.username }}'>
				
				<label for='text'>Content: </label><br>
				<textarea cols='100' rows='20'></textarea><br><br>
				
				<input type='submit' value='Submit' class='btn'>
				
				
			</form>
			
		
		</div>
		
	</body>
</html>

blog/templates/website/writterspage.html
{% extends 'website/base.html' %}
{% load static %}

{% block content_space %}
	<div id="writter_info">
		<div class="writter_image">
			<img src="{{MEDIA_URL}}{{writter.photo}}" class="writter_image">
		</div>
		
		<div>
			Name: {{writter.name}}<br>
			Member Since: {{writter.date_added}}<br>
			
			Description: {{writter.description}}
		</div>
		
		
	</div>
{% endblock %}

blog/templates/website/wt_area.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<style>
			header{
				height:50px;
				color:white;
				padding: 20px 40px 0px 40px;
			}
			
			#pubs_div{
				width:30%;
				height:100%;
				border-right: 1px solid;
				background-color:rgba(200,200,200,0.5);
				display:inline;
				float:left;
			}
			
			#form_div{
				width:65%;
				margin: 0 2% 0 1%;
				background-color:rgba(255,255,0,0.1);
				float:right;
			}
			
			a{
				text-decoration:none;
			}
			
			header p{
				display:inline;
			}
			
			header a{
				float: right;
			}
		</style>
	</head>
	<body>
		<header>
			<p>Hello, {{ request.user.username }} </p>
			
			<a href="{% url 'logout' %}">Log out</a>
		</header>
		
		<div id='pubs_div'>
			{% if user.is_authenticated %}
				<h1>You are authenticated and logged in</h1>
			{% else %}
				<h1>You aren't authenticated and not logged in. Try again</h1>
			{% endif %}
			
			<h3 class='title'>My Pubs</h3>
			{% if pubs %}
				<form method='POST' action='whatdo/'>
					{% csrf_token %}
				
					What to do: <select name='whatdo'>
						<option value='delete'>Delete the selected pubs</option>					
					</select> 
					<input type='submit' value='Go'><br><br>
					
					{% for pub in pubs %}
						<input type='checkbox' id='{{ pub.title }}' multiple name='pubs' value='{{ pub.title }}'>
						<a href="{% url 'website:updatepub' pub.id %}"}>{{ pub.title }}</a><br><br>
					{% endfor %}
				</form>
			{% endif %}
		</div>
		
		<div id='form_div'>
			<h3 class='title'>Add New Pub</h3>
			
			<form method='post' action='postpub/' id='userform'>
				{% csrf_token %}
				
				{{ form.as_p }}
				
				<input type='submit' value='Submit' class='btn'>
			</form>
			
			<!-- <form method='post' action='postpub/' id='userform'>
				{% csrf_token %}
			
			
				<label for='title'>Title: </label>
				<input type='text' name='title'><br><br>
				
				<label for='date'>Date: </label>
				<input type='date' name='date'><br><br>
				
				<label for='image'>Photo: </label>
				<input type='file' name='image'><br><br>
				
				<input type='hidden' name='writter' value='{{ request.user.id }}'>
				
				<label for='text'>Content: </label><br>
				<textarea cols='100' rows='20' id='text' name='text' form='userform'></textarea><br><br>
				
				<input type='submit' value='Submit' class='btn'>
	
			</form>
			
			-->
	
		</div>
		
	</body>
</html>